[Wed Jun 04 14:47:03 2014] [error] [client 192.168.10.1] attempt to invoke directory as script: /var/www/example.ru/cgi-bin/
[Wed Jun 04 16:40:24 2014] [error] [client 192.168.10.1] File does not exist: /var/www/example.ru/favicon.ico
[Wed Jun 04 16:43:30 2014] [error] [client 192.168.10.1] malformed header from script. Bad header= : hello.py
[Wed Jun 04 16:44:18 2014] [error] [client 192.168.10.1] malformed header from script. Bad header= : hello.py
[Wed Jun 04 16:44:59 2014] [error] [client 192.168.10.1] malformed header from script. Bad header=Hello, world!: hello.py
[Wed Jun 04 16:46:28 2014] [error] [client 192.168.10.1] script not found or unable to stat: /var/www/example.ru/cgi-bin/hello.py
[Wed Jun 04 17:07:31 2014] [error] [client 192.168.10.1] Traceback (most recent call last):
[Wed Jun 04 17:07:31 2014] [error] [client 192.168.10.1]   File "/var/www/example.ru/cgi-bin/test.py", line 5, in <module>
[Wed Jun 04 17:07:31 2014] [error] [client 192.168.10.1]     import MySQLdb
[Wed Jun 04 17:07:31 2014] [error] [client 192.168.10.1] ImportError: No module named MySQLdb
[Wed Jun 04 17:07:31 2014] [error] [client 192.168.10.1] Premature end of script headers: test.py
[Wed Jun 04 17:13:05 2014] [error] [client 192.168.10.1] File does not exist: /var/www/example.ru/favicon.ico
[Tue Jun 17 09:54:06 2014] [error] [client 192.168.10.1] File does not exist: /var/www/example.ru/favicon.ico
[Tue Jun 17 15:03:36 2014] [error] [client 192.168.10.1] File does not exist: /var/www/example.ru/favicon.ico
[Fri Sep 19 12:03:25 2014] [error] [client 127.0.0.1] File does not exist: /var/www/example.ru/favicon.ico
[Fri Sep 19 12:05:03 2014] [error] [client 127.0.0.1] Traceback (most recent call last):
[Fri Sep 19 12:05:03 2014] [error] [client 127.0.0.1]   File "/var/www/example.ru/cgi-bin/test.py", line 14, in <module>
[Fri Sep 19 12:05:03 2014] [error] [client 127.0.0.1]     cursor = connection.cursor()
[Fri Sep 19 12:05:03 2014] [error] [client 127.0.0.1] NameError: name 'connection' is not defined
[Fri Sep 19 12:06:41 2014] [error] [client 127.0.0.1] attempt to invoke directory as script: /var/www/example.ru/cgi-bin/, referer: http://www.example.ru/
[Fri Sep 19 12:10:26 2014] [error] [client 127.0.0.1] attempt to invoke directory as script: /var/www/example.ru/cgi-bin/
[Fri Sep 19 12:10:30 2014] [error] [client 127.0.0.1] Traceback (most recent call last):
[Fri Sep 19 12:10:30 2014] [error] [client 127.0.0.1]   File "/var/www/example.ru/cgi-bin/test.py", line 14, in <module>
[Fri Sep 19 12:10:30 2014] [error] [client 127.0.0.1]     cursor = connection.cursor()
[Fri Sep 19 12:10:30 2014] [error] [client 127.0.0.1] NameError: name 'connection' is not defined
[Fri Sep 19 17:23:05 2014] [error] [client 127.0.0.1] attempt to invoke directory as script: /var/www/example.ru/cgi-bin/
[Fri Sep 19 17:34:52 2014] [error] [client 127.0.0.1] Premature end of script headers: test2.py, referer: http://www.example.ru/
[Fri Sep 19 17:35:50 2014] [error] [client 127.0.0.1] Premature end of script headers: test2.py, referer: http://www.example.ru/
[Fri Sep 19 17:36:08 2014] [error] [client 127.0.0.1] Premature end of script headers: test2.py, referer: http://www.example.ru/
[Fri Sep 19 17:37:15 2014] [error] [client 127.0.0.1] Premature end of script headers: test2.py, referer: http://www.example.ru/
[Fri Sep 19 17:39:25 2014] [error] [client 127.0.0.1] malformed header from script. Bad header=<html>: test2.py, referer: http://www.example.ru/
[Fri Sep 19 17:40:08 2014] [error] [client 127.0.0.1] Premature end of script headers: test2.py, referer: http://www.example.ru/
[Fri Sep 19 17:41:40 2014] [error] [client 127.0.0.1] Premature end of script headers: test2.py, referer: http://www.example.ru/
[Thu Oct 09 16:00:43 2014] [error] [client 192.168.10.1] Traceback (most recent call last):, referer: http://www.cgi.ru/
[Thu Oct 09 16:00:43 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/test.py", line 14, in <module>, referer: http://www.cgi.ru/
[Thu Oct 09 16:00:43 2014] [error] [client 192.168.10.1]     cursor = connection.cursor(), referer: http://www.cgi.ru/
[Thu Oct 09 16:00:43 2014] [error] [client 192.168.10.1] NameError: name 'connection' is not defined, referer: http://www.cgi.ru/
[Thu Oct 09 19:47:42 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Thu Oct 09 21:18:45 2014] [error] [client 192.168.10.1] (13)Permission denied: exec of '/var/www/cgi.ru/cgi-bin/index.html' failed
[Thu Oct 09 21:18:45 2014] [error] [client 192.168.10.1] Premature end of script headers: index.html
[Thu Oct 09 21:18:56 2014] [error] [client 192.168.10.1] attempt to invoke directory as script: /var/www/cgi.ru/cgi-bin/
[Thu Oct 09 21:19:04 2014] [error] [client 192.168.10.1] (13)Permission denied: exec of '/var/www/cgi.ru/cgi-bin/index.html' failed
[Thu Oct 09 21:19:04 2014] [error] [client 192.168.10.1] Premature end of script headers: index.html
[Thu Oct 09 21:21:47 2014] [error] [client 127.0.0.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Thu Oct 09 21:21:47 2014] [error] [client 127.0.0.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Thu Oct 09 21:23:01 2014] [error] [client 127.0.0.1] (13)Permission denied: exec of '/var/www/cgi.ru/cgi-bin/resp.txt' failed, referer: http://www.cgi.ru/
[Thu Oct 09 21:23:01 2014] [error] [client 127.0.0.1] Premature end of script headers: resp.txt, referer: http://www.cgi.ru/
[Thu Oct 09 21:23:26 2014] [error] [client 127.0.0.1] (13)Permission denied: exec of '/var/www/cgi.ru/cgi-bin/resp.txt' failed, referer: http://127.0.0.1/cgi.ru/
[Thu Oct 09 21:23:26 2014] [error] [client 127.0.0.1] Premature end of script headers: resp.txt, referer: http://127.0.0.1/cgi.ru/
[Thu Oct 09 21:50:28 2014] [error] [client 127.0.0.1] (13)Permission denied: exec of '/var/www/cgi.ru/cgi-bin/resp.txt' failed, referer: http://www.cgi.ru/
[Thu Oct 09 21:50:28 2014] [error] [client 127.0.0.1] Premature end of script headers: resp.txt, referer: http://www.cgi.ru/
[Thu Oct 09 21:51:26 2014] [error] [client 127.0.0.1] Traceback (most recent call last):, referer: http://www.cgi.ru/
[Thu Oct 09 21:51:26 2014] [error] [client 127.0.0.1]   File "/var/www/cgi.ru/cgi-bin/getb.py", line 6, in <module>, referer: http://www.cgi.ru/
[Thu Oct 09 21:51:26 2014] [error] [client 127.0.0.1]     import forest as f, referer: http://www.cgi.ru/
[Thu Oct 09 21:51:26 2014] [error] [client 127.0.0.1]   File "/var/www/cgi.ru/cgi-bin/forest.py", line 4, in <module>, referer: http://www.cgi.ru/
[Thu Oct 09 21:51:26 2014] [error] [client 127.0.0.1]     import psycopg2, referer: http://www.cgi.ru/
[Thu Oct 09 21:51:26 2014] [error] [client 127.0.0.1] ImportError: No module named 'psycopg2', referer: http://www.cgi.ru/
[Thu Oct 09 21:51:26 2014] [error] [client 127.0.0.1] Premature end of script headers: getb.py, referer: http://www.cgi.ru/
[Thu Oct 09 21:53:52 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/resp.txt, referer: http://www.cgi.ru/
[Thu Oct 09 21:55:10 2014] [error] [client 192.168.10.1] Traceback (most recent call last):
[Thu Oct 09 21:55:10 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/getb.py", line 6, in <module>
[Thu Oct 09 21:55:10 2014] [error] [client 192.168.10.1]     import forest as f
[Thu Oct 09 21:55:10 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/forest.py", line 4, in <module>
[Thu Oct 09 21:55:10 2014] [error] [client 192.168.10.1]     import psycopg2
[Thu Oct 09 21:55:10 2014] [error] [client 192.168.10.1] ImportError: No module named 'psycopg2'
[Thu Oct 09 21:55:10 2014] [error] [client 192.168.10.1] Premature end of script headers: getb.py
[Thu Oct 09 21:56:03 2014] [error] [client 192.168.10.1] Traceback (most recent call last):
[Thu Oct 09 21:56:03 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/getb.py", line 6, in <module>
[Thu Oct 09 21:56:03 2014] [error] [client 192.168.10.1]     import forest as f
[Thu Oct 09 21:56:03 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/forest.py", line 4, in <module>
[Thu Oct 09 21:56:03 2014] [error] [client 192.168.10.1]     import psycopg2
[Thu Oct 09 21:56:03 2014] [error] [client 192.168.10.1] ImportError: No module named 'psycopg2'
[Thu Oct 09 21:56:03 2014] [error] [client 192.168.10.1] Premature end of script headers: getb.py
[Thu Oct 09 21:56:23 2014] [error] [client 192.168.10.1] Traceback (most recent call last):
[Thu Oct 09 21:56:23 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/getb.py", line 6, in <module>
[Thu Oct 09 21:56:23 2014] [error] [client 192.168.10.1]     import forest as f
[Thu Oct 09 21:56:23 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/forest.py", line 4, in <module>
[Thu Oct 09 21:56:23 2014] [error] [client 192.168.10.1]     import psycopg2
[Thu Oct 09 21:56:23 2014] [error] [client 192.168.10.1] ImportError: No module named 'psycopg2'
[Thu Oct 09 21:56:23 2014] [error] [client 192.168.10.1] Premature end of script headers: getb.py
[Thu Oct 09 21:56:34 2014] [error] [client 192.168.10.1] Premature end of script headers: test.py
[Thu Oct 09 21:56:51 2014] [error] [client 192.168.10.1] Premature end of script headers: test.py
[Thu Oct 09 21:58:06 2014] [error] [client 192.168.10.1] Traceback (most recent call last):
[Thu Oct 09 21:58:06 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/getb.py", line 6, in <module>
[Thu Oct 09 21:58:06 2014] [error] [client 192.168.10.1]     import forest as f
[Thu Oct 09 21:58:06 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/forest.py", line 4, in <module>
[Thu Oct 09 21:58:06 2014] [error] [client 192.168.10.1]     import psycopg2
[Thu Oct 09 21:58:06 2014] [error] [client 192.168.10.1] ImportError: No module named 'psycopg2'
[Thu Oct 09 21:58:06 2014] [error] [client 192.168.10.1] Premature end of script headers: getb.py
[Thu Oct 09 21:58:17 2014] [error] [client 192.168.10.1] Traceback (most recent call last):
[Thu Oct 09 21:58:17 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/getb.py", line 6, in <module>
[Thu Oct 09 21:58:17 2014] [error] [client 192.168.10.1]     import forest as f
[Thu Oct 09 21:58:17 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/forest.py", line 4, in <module>
[Thu Oct 09 21:58:17 2014] [error] [client 192.168.10.1]     import psycopg2
[Thu Oct 09 21:58:17 2014] [error] [client 192.168.10.1] ImportError: No module named 'psycopg2'
[Thu Oct 09 21:58:17 2014] [error] [client 192.168.10.1] Premature end of script headers: getb.py
[Thu Oct 09 21:58:29 2014] [error] [client 192.168.10.1] Traceback (most recent call last):
[Thu Oct 09 21:58:29 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/getb.py", line 6, in <module>
[Thu Oct 09 21:58:29 2014] [error] [client 192.168.10.1]     import forest as f
[Thu Oct 09 21:58:29 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/forest.py", line 4, in <module>
[Thu Oct 09 21:58:29 2014] [error] [client 192.168.10.1]     import psycopg2
[Thu Oct 09 21:58:29 2014] [error] [client 192.168.10.1] ImportError: No module named 'psycopg2'
[Thu Oct 09 21:58:29 2014] [error] [client 192.168.10.1] Premature end of script headers: getb.py
[Thu Oct 09 21:59:28 2014] [error] [client 192.168.10.1] Traceback (most recent call last):
[Thu Oct 09 21:59:28 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/getb.py", line 16, in <module>
[Thu Oct 09 21:59:28 2014] [error] [client 192.168.10.1]     import forest as f
[Thu Oct 09 21:59:28 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/forest.py", line 4, in <module>
[Thu Oct 09 21:59:28 2014] [error] [client 192.168.10.1]     import psycopg2
[Thu Oct 09 21:59:28 2014] [error] [client 192.168.10.1] ImportError: No module named 'psycopg2'
[Thu Oct 09 22:00:03 2014] [error] [client 192.168.10.1] Traceback (most recent call last):
[Thu Oct 09 22:00:03 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/getb.py", line 6, in <module>
[Thu Oct 09 22:00:03 2014] [error] [client 192.168.10.1]     import forest as f
[Thu Oct 09 22:00:03 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/forest.py", line 4, in <module>
[Thu Oct 09 22:00:03 2014] [error] [client 192.168.10.1]     import psycopg2
[Thu Oct 09 22:00:03 2014] [error] [client 192.168.10.1] ImportError: No module named 'psycopg2'
[Thu Oct 09 22:00:03 2014] [error] [client 192.168.10.1] Premature end of script headers: getb.py
[Thu Oct 09 22:02:08 2014] [error] [client 192.168.10.1] Traceback (most recent call last):
[Thu Oct 09 22:02:08 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/getb.py", line 6, in <module>
[Thu Oct 09 22:02:08 2014] [error] [client 192.168.10.1]     import forest as f
[Thu Oct 09 22:02:08 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/forest.py", line 4, in <module>
[Thu Oct 09 22:02:08 2014] [error] [client 192.168.10.1]     import psycopg2
[Thu Oct 09 22:02:08 2014] [error] [client 192.168.10.1] ImportError: No module named 'psycopg2'
[Thu Oct 09 22:02:08 2014] [error] [client 192.168.10.1] Premature end of script headers: getb.py
[Thu Oct 09 22:02:08 2014] [error] [client 192.168.10.1] Traceback (most recent call last):
[Thu Oct 09 22:02:08 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/getb.py", line 6, in <module>
[Thu Oct 09 22:02:08 2014] [error] [client 192.168.10.1]     import forest as f
[Thu Oct 09 22:02:08 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/forest.py", line 4, in <module>
[Thu Oct 09 22:02:08 2014] [error] [client 192.168.10.1]     import psycopg2
[Thu Oct 09 22:02:08 2014] [error] [client 192.168.10.1] ImportError: No module named 'psycopg2'
[Thu Oct 09 22:02:08 2014] [error] [client 192.168.10.1] Premature end of script headers: getb.py
[Thu Oct 09 22:02:09 2014] [error] [client 192.168.10.1] Traceback (most recent call last):
[Thu Oct 09 22:02:09 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/getb.py", line 6, in <module>
[Thu Oct 09 22:02:09 2014] [error] [client 192.168.10.1]     import forest as f
[Thu Oct 09 22:02:09 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/forest.py", line 4, in <module>
[Thu Oct 09 22:02:09 2014] [error] [client 192.168.10.1]     import psycopg2
[Thu Oct 09 22:02:09 2014] [error] [client 192.168.10.1] ImportError: No module named 'psycopg2'
[Thu Oct 09 22:02:09 2014] [error] [client 192.168.10.1] Premature end of script headers: getb.py
[Thu Oct 09 22:02:09 2014] [error] [client 192.168.10.1] Traceback (most recent call last):
[Thu Oct 09 22:02:09 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/getb.py", line 6, in <module>
[Thu Oct 09 22:02:09 2014] [error] [client 192.168.10.1]     import forest as f
[Thu Oct 09 22:02:09 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/forest.py", line 4, in <module>
[Thu Oct 09 22:02:09 2014] [error] [client 192.168.10.1]     import psycopg2
[Thu Oct 09 22:02:09 2014] [error] [client 192.168.10.1] ImportError: No module named 'psycopg2'
[Thu Oct 09 22:02:09 2014] [error] [client 192.168.10.1] Premature end of script headers: getb.py
[Thu Oct 09 22:02:10 2014] [error] [client 192.168.10.1] Traceback (most recent call last):
[Thu Oct 09 22:02:10 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/getb.py", line 6, in <module>
[Thu Oct 09 22:02:10 2014] [error] [client 192.168.10.1]     import forest as f
[Thu Oct 09 22:02:10 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/forest.py", line 4, in <module>
[Thu Oct 09 22:02:10 2014] [error] [client 192.168.10.1]     import psycopg2
[Thu Oct 09 22:02:10 2014] [error] [client 192.168.10.1] ImportError: No module named 'psycopg2'
[Thu Oct 09 22:02:10 2014] [error] [client 192.168.10.1] Premature end of script headers: getb.py
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1] Traceback (most recent call last):
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/getb.py", line 6, in <module>
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1]     import forest as f
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/forest.py", line 4, in <module>
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1]     import psycopg2
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1] ImportError: No module named 'psycopg2'
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1] Premature end of script headers: getb.py
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1] Traceback (most recent call last):
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/getb.py", line 6, in <module>
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1]     import forest as f
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/forest.py", line 4, in <module>
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1]     import psycopg2
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1] ImportError: No module named 'psycopg2'
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1] Premature end of script headers: getb.py
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1] Traceback (most recent call last):
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/getb.py", line 6, in <module>
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1]     import forest as f
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/forest.py", line 4, in <module>
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1]     import psycopg2
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1] ImportError: No module named 'psycopg2'
[Thu Oct 09 22:02:11 2014] [error] [client 192.168.10.1] Premature end of script headers: getb.py
[Sat Oct 18 09:43:39 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Sat Oct 18 14:33:53 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Sat Oct 18 14:34:21 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Sat Oct 18 14:39:13 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Sat Oct 18 14:40:36 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Sat Oct 18 14:40:41 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Sat Oct 18 14:43:37 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Sat Oct 18 14:50:15 2014] [error] [client 192.168.10.1] attempt to invoke directory as script: /var/www/cgi.ru/cgi-bin/, referer: http://www.cgi.ru/
[Sat Oct 18 14:50:15 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Sat Oct 18 14:52:32 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Sat Oct 18 14:52:42 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Sat Oct 18 14:54:27 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Sat Oct 18 14:55:02 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Sat Oct 18 15:01:41 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Sat Oct 18 15:02:55 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Sat Oct 18 15:08:01 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Sat Oct 18 15:10:04 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Sat Oct 18 15:10:38 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Sat Oct 18 15:11:04 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Sat Oct 18 15:11:52 2014] [error] [client 192.168.10.1] File does not exist: /var/www/cgi.ru/favicon.ico
[Mon Oct 20 17:20:34 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/getb.py", line 53, referer: http://www.cgi.ru/
[Mon Oct 20 17:20:34 2014] [error] [client 192.168.10.1]     print("\\, referer: http://www.cgi.ru/
[Mon Oct 20 17:20:34 2014] [error] [client 192.168.10.1]     ^, referer: http://www.cgi.ru/
[Mon Oct 20 17:20:34 2014] [error] [client 192.168.10.1] IndentationError: expected an indented block, referer: http://www.cgi.ru/
[Mon Oct 20 17:20:34 2014] [error] [client 192.168.10.1] Premature end of script headers: getb.py, referer: http://www.cgi.ru/
[Mon Oct 20 17:21:41 2014] [error] [client 192.168.10.1]   File "/var/www/cgi.ru/cgi-bin/getb.py", line 53, referer: http://www.cgi.ru/
[Mon Oct 20 17:21:41 2014] [error] [client 192.168.10.1]     print("\\, referer: http://www.cgi.ru/
[Mon Oct 20 17:21:41 2014] [error] [client 192.168.10.1]     ^, referer: http://www.cgi.ru/
[Mon Oct 20 17:21:41 2014] [error] [client 192.168.10.1] IndentationError: expected an indented block, referer: http://www.cgi.ru/
[Mon Oct 20 17:21:41 2014] [error] [client 192.168.10.1] Premature end of script headers: getb.py, referer: http://www.cgi.ru/
